### PR TITLE
Simplification of console commands + new command : reloadall + deprecated

### PR DESCRIPTION
**Pull request by vincentducorps**
Useful when you do a lot of testing ;)

### CODE REVIEW

**Comment by Freeeaky** [comment]
Awesome work! Thanks a lot!

Do you mind keeping the old commands (load_addon) aswell, but with a "deprecated" notice?

**Comment by vincentducorps** [comment]
Yes, you're absolutely right!

I've worked on a "deprecated" function, I commit this in 2 minutes!

**Comment by Freeeaky** [comment]
Sorry! Never saw that you committed something.
I was just about to ask if you were still active lol

Happy new year by the way. Merging now!

**Comment by vincentducorps** [comment]
Hey Jan,
Happy new year too ! :) 

I also was wondering whether you were still active !

Have you time and the will to make GTALua really awesome and powerful?
If so, I have some ideas and I want to talk to you! :)

**Comment by Freeeaky** [comment]
Yea, sorry again.
Currently someone else is also working on the project, his name is Mockba. We are patching up GTALua and our goal is to release a new version in the next few weeks.

**Pull request merged**
