### PR TITLE
Updated .ini files, added b617 to the supported versions and added the 3 new vehicles.

### PR DESCRIPTION
**Pull request by MockbaTheBorg**
Updated .ini files, added b617 to the supported versions and added the 3 new vehicles.

### CODE REVIEW

**Comment by Freeeaky** [comment]
Hey, thanks! There is one thing I noticed tho:

https://github.com/MockbaTheBorg/GTALua/blob/f65bf63601bfee7f7a79f67e16542cbaa3556970/build/GTALua/internal/game/Vehicle.lua#L175

Why are you using self.Hash here? That shouldn't even be defined! You should use the getter function.

About the getter function: There is a GetModel function (from Entity class) - that should work for Vehicles too, so there is no need to define a new function called GetModelHash.

**Comment by MockbaTheBorg** [comment]
True, this is leftover of my cut&paste from my test files.
I need to fix it or it will cause errors... wait for the next commit, I will have it corrected.

**Comment by MockbaTheBorg** [comment]
I have corrected Vehicle.lua to use the GetModel() function inherited from Entity. I have also added the different SetNotNeeded for each one if the object types.

**Comment by Freeeaky** [comment]
Thanks! Merging now.

**Pull request merged**
