### PR TITLE
Update gui.NotifyAboveMap(text, blink)

### PR DESCRIPTION
**Pull request by vincentducorps**
I'm not sure of my error message...

What do you think about?

Link to the wiki ?

### CODE REVIEW

**Comment by Freeeaky** [comment]
So the second argument is not time? Are you sure it's blink?

**Comment by vincentducorps** [comment]
Yep, I tried it yesterday.

-> http://www.dev-c.com/nativedb/func/info/2ed7843f8f801023 (scroll down to UI::_DRAW_NOTIFICATION)

**Comment by Freeeaky** [comment]
I suggest that we don't print anything. We should just ignore the numbers and assume false (don't blink)

**Comment by vincentducorps** [comment]
Perhaps simply indicate the depreciation on the wiki?

As you want, I don't know... :)

**Comment by Freeeaky** [comment]
Thanks again!

**Pull request merged**
